### ISSUE TITLE
Migration to TypeORM

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#149]
**Is your feature request related to a problem? Please describe.**
Zkopru should be run on mobile or browser clients. Current Prisma for the database layer is not supporting react-native sqlite clients & leveldb. It seems it's in the queue https://github.com/prisma/prisma/issues/5011 but we're not sure when Prisma will support leveldb for the browser side.

**Describe the solution you'd like**
TypeORM is a bit more complex than Prisma but it supports react native & leveldb. So we can create a separate "database" package that has an abstract API layer to query with the databases using TypeORM or even Prisma. Maybe in the end we can just drop Prisma and fully migrate to TypeORM, but it'll be good to keep the current Prisma implementation for a graceful migration.

**Comment by JChanceHud** [comment]
Hey @wanseob I'm working on the client implementation of Zkopru in browser. I think it's important that it's possible to run a client in a variety of environments. Instead of relying on Prisma or TypeORM who only support some databases, it would be nice to define an interface for storage connectors that can be implemented using any underlying storage system.

This would let us support things like [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API), or a simple in memory DB for testing.

Such an interface might look like this:

```ts
type WhereClause = { [key: string]: any }

interface DataDelegate {
  create: (collection: string, doc: Object) => Promise<Object>
  findOne: (collection: string, where: WhereClause) => Promise<Object>
  // retrieve many documents matching a where clause
  findMany: (collection: string, where: WhereClause, options: {
    orderBy?: {
      [key: string]: 'asc' | 'desc'
    },
    take?: number,
  }) => Promise<Object[]>
  // count document matching a where clause
  count: (collection: string, where: WhereClause) => Promise<number>
  // update some documents returning the number updated
  update: (collection: string, where: WhereClause, changes: Object) => Promise<number>
  // update or create some documents
  upsert: (collection: string, where: WhereClause, options: {
    update: Object,
    create: Object,
  }) => Promise<{ created: number, updated: number }>
  // request that an index be created between some keys, if supported
  ensureIndex: (collection: string, name: string, keys: string[]) => void
}

```

A standard set of tests could be written so that each connector works predictably. Specifically the `WhereClause` would need to be tested for the `AND`, `OR` and `IN` operators.

Right now the only option for implementing a browser based wallet using the existing `core` package is storing an sqlite db in localstorage, though I'm not sure how feasible this is.

**Comment by wanseob** [comment]
I strongly support your idea. So currently, the possible option for us is

1. Running a full node in CLI and run JsonRPC API that allows access only for configured IPs.
2. Run web application using ZkopruClient https://github.com/zkopru-network/zkopru/issues/156. The Zkopru client should be connected to the JsonRPC endpoint.

After refactoring the storage connector, we have another option like
1. Running the "core" package in anywhere. In web browser it'll use indexedDB for its storage. Otherwise, SQLite for React native, Postgres for desktop.
2. Run UI using ZkopruClient & the client directly calls the core APIs in the same process.

Does this make sense?

**Comment by JChanceHud** [comment]
>  After refactoring the storage connector, we have another option like
    1. Running the "core" package in anywhere. In web browser it'll use indexedDB for its storage. Otherwise, SQLite for React native, Postgres for desktop.
    2. Run UI using ZkopruClient & the client directly calls the core APIs in the same process.

Yes, that makes sense. This will let each environment sync the actual chain (we'll probably need to come up with some fast sync method in the future).

Should I work on this? It blocks the wallet client.

**Comment by wanseob** [comment]
Oh please go for this if it's blocking you. I'm now spending more time on the specification document.
