### ISSUE TITLE
Push pattern in the mass migration can lock fund forever.

### ISSUE THREAD

**Issue by wanseob** [zkopru-network/zkopru#201]
**Describe the bug**
[Push pattern in the mass migration execution](https://github.com/zkopru-network/zkopru/blob/97e315952badf645dacf0da6af61dff6c662ece1/packages/contracts/contracts/zkopru/controllers/Migratable.sol#L49) can lock the mass migration forever.

To attack the network,
1. create an ERC20 contract that always fails after 1 month.
2. register the ERC20 on Zkopru and create deposit.
3. After 1 month, if there are lots of migrations, create a migration using that malicious ERC20 token.
4. MassMigration that includes the malicious leaf will always fail so the assets in the same mass migration will be locked forever.

To fix this issue, we should redesign the migration process with pull pattern.

**Comment by JChanceHud** [comment]
This isn't too bad, maybe instead of redesigning the migration process we could add some safety checks to the push process like allowing the migration to occur in multiple transactions.

Something like [this](https://github.com/zkopru-network/zkopru/blob/develop/packages/contracts/contracts/consensus/BurnAuction.sol#L295) might make sense. There could be an iterator that tries the migration and skips tokens that fail (allowing them to be retried later, or marking them as failed). This would just require users to verify the token they're using (like Uniswap), which we could build into the UI.

**Comment by nginnever** [comment]
I worry about "skipping transactions that fail". Consider another attack scenario.

1. Create an attack token that has a switch the attacker can flip that will jump execution to a long loop intended to consume gas
2. register token
3. flip switch
4. now you can't skip the transaction since it won't fail, it will just consume too much gas to allow the migration function to operate.

**Comment by JChanceHud** [comment]
Absolutely, I should clarify that running out of gas is a failure case. So ideally the migrate function looks at an array of erc20's and accepts a range to migrate in a single transaction.

So each step below might be a transaction:

1. Start migration (no token interaction)
2. Move Ether
3. Move tokens by specifying a range
3a. Estimate gas by looking for tokens causing out of gas errors
3b. Send multiple transactions to exclude failing tokens e.g. of 20 tokens with token 8 failing migrate 0-7, then 9-19
4. Move NFTs using above logic
5. Mark migration as complete (if needed)

This is a much more involved migration but would be safe against malicious contracts.

**Comment by rairyx** [comment]
Transfer() also would cause out of gas(the default gas of 2300 for fallback function might increase by spec change) if there are many ERC20 tokens in the migration.

**Comment by wanseob** [comment]
Here are my thoughts.

Migrating NFT anyway always need "transfer" per each NFT. That means it does not make any sense for mass migration. Therefore, using mass migration only for ERC20 & Ether can solve this problem.

In this case, every mass migration will have each `destination` and `token` address. so the structure will look like
```
struct MassDeposit {
    bytes32 merged;
    uint256 fee;
}

struct MigrationAsset {
    uint256 eth; // eth amount
    address token; // ERC20 token address
    uint256 amount; // ERC20 token amount
}

struct MassMigration {
    address destination;
    MigrationAsset asset;
    MassDeposit depositForDest;
}
```

Then, we can store the 'migrationRoot' of the block header only since it's a merkle root of `MassMigration[] migrations`.

Then, using a pull pattern from the dest contract, the dest contract calls a function like
```solidity
function pullMigration(MassMigration memory migration, bytes32 migrationRoot, bytes32[] memory merkleProof) {
    // mark as the hash(migration) is spent.
}
```
With this refactoring we won't have any push pattern and the malicious contract cannot affect other tokens.

**Comment by wanseob** [comment]
BTW with this pull pattern we can improve
1. no push pattern and it removes the malicious contract attack.
2. use only 1 SSTORE / block. Previously it uses `massMigrations.length` times of SSTORE.
3. No need for whitelisting for the migration since the source and dest are obvious & migration moves only 1 type of asset.

BTW NFT migration should be done w/ manually via withdrawal & re-depositing to the dest network.
