### ISSUE TITLE
Withdrawal prepay logic

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#274]
To fulfill a prepay request a user must communicate with the user making the withdrawal in order to receive a signature. This makes it difficult for counter parties to fulfill requests.

Instead I propose that we remove the signature requirement and include the prepay parameters in the [withdrawal hash](https://github.com/zkopru-network/zkopru/blob/develop/packages/contracts/contracts/zkopru/controllers/UserInteractable.sol#L140) public data. All withdrawals must include a prepay fee and expiration date (defaulting to `0`).

With this logic we can remove the signature requirement and verify the parameters in the withdrawal hash on chain.

Related #33

**Comment by JChanceHud** [comment]
This may be a good time to switch from a prepay expiration date to a decay curve (where the prepayer receives less of the reward the later they pay).

**Comment by JChanceHud** [comment]
A different approach to solve the communication problem might be removing the `prepayer` field from the signature and passing it as calldata to the `withdraw` function (if prepay is allowed), and then emitting an event with this data.

A prepayer would take the emitted signature and pass it to the `payInAdvance` function.

This way the prepay parameters can be verified without needing to change the withdrawal hash, and without the withdrawer and prepayer needing to communicate.

**Comment by wanseob** [comment]
@JChanceHud 
Thank u Chance for bringing this idea. 
First, I tried to remove the prepay fee from the withdrawal hash for some cases like
1. I made a withdrawal.
2. But I wanna speed up my withdrawal
3. Then request prepay of my withdrawal to others
In this case, if we include that process when we create the l2 tx, there is no way to speed up my withdrawal using prepay feature.

Rather than, I wanna propose adding a condition 
```
prepayRequest.prepayer == msg.sender || prepayRequest.prepayer == address(0)
```
https://github.com/zkopru-network/zkopru/blob/13c9dd2f2143b0c7f01adb02629c9a902d4c4694/packages/contracts/contracts/zkopru/controllers/UserInteractable.sol#L154-L157

In this case, the withdrawer is saying like "anyone who wants to prepay can execute this tx". How does this sound?

**Comment by JChanceHud** [comment]
Yes, this makes sense. The problem we have is data availability, how will a potential prepayer get the signature?

What do you think of adding an optional argument to the `withdraw` function, and maybe another function like `requestPrepay` that can be called after the withdrawal request?

**Comment by wanseob** [comment]
I'm just recapping my opinion we had a talk through messegner here :)
1. we can utilize withdrawal tx's memo field for the signature data availability
2. imo, to request prepay I think we should host a separate server to avoid spending additional gas for this
