### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#304]
Our docker images are having trouble installing python. This is causing some CI tasks to fail. It seems Alpine linux no longer aliases the package `python` to `python2`.

[Related](https://dockerquestions.com/2021/11/08/docker-alpine-unable-to-select-packages-python-no-such-package-while-building-image-for-arm/)

Our docker images are also using `node:12-alpine`, perhaps we should bump to node 14 or 16?

**Comment by sifnoc** [comment]
FYI, the `node:16-stretch-slim` image works for me.

but you already fixed it ;)

**Comment by JChanceHud** [comment]
Yep, the Debian variant is good too. Right now we have some images using Alpine and some using Debian, we should probably use one or the other in the future.

**Comment by praneethmendu** [comment]
Hi, but abrupt of me walking into this conversation, but I have been looking at the dockerfiles for a while ([298](https://github.com/zkopru-network/zkopru/issues/298)) and I understood a few things.

- alpine now uses python2 and python3 as package names instead of python

- we are currently installing python (along with other build tools )as a virtual package, using it to install truffle and deleting it immediately after to save space. But down the line we also need it for yarn install which is what keeps failing.

- debian ships with python but alpine does not.|

Now I have a solution, but I am a noob in docker so maybe we can set a pattern and I can adapt all the files accordingly, right now I have time and I would like to contribute. I am struggling with the tests a bit to make a pr but this is the idea:
<img width="1090" alt="Screen Shot 2021-11-10 at 12 36 31 PM" src="https://user-images.githubusercontent.com/21146348/141106470-61f27049-beb4-4d3d-a525-416f8f2433c2.png">

**Comment by JChanceHud** [comment]
@praneethmendu This is a good solution, my only issue is with the switch from python2 to python3. python3 doesn't add a `python` executable to the path inside the container so any build scripts relying on it may fail. Aside from that this approach works well.

Feel free to open a PR with it, or to consolidate all our images to alpine or stretch-slim (up to you which).

**Comment by praneethmendu** [comment]
@JChanceHud in this specific case ( Contract.dockerfile with node 16 ) truffle required python3 for some reason, also `yarn install` seems to work fine with python3 in path

I've run into these problems when `yarn develop` runs docker-compose but currently all the CI tasks are passing. should we have tests to emulate that or am I missing something?

I did make a [pr](https://github.com/zkopru-network/zkopru/pull/306) but I could not pass the precommit ([unit tests under core for light node and full node](https://pastebin.com/tgp3SKPu)). Do I need to run some service or script before I do this ? I have only run the following things:
```
yarn bootstrap
yarn build
yarn develop
```

```
cd packages/circuits
yarn setup
yarn build-keys
yarn postbuild-keys
```

Most of our docker images have alpine with only 2 using Debian so I will change those in a future PR

**Comment by JChanceHud** [comment]
@praneethmendu Cool, the tests for the PR seem to be passing. Are they failing on your local machine? If so running the commands from the CI config file usually gets things working locally. The commands you posted look about right

I think adding a pipeline to test `yarn develop` in the CI is a good idea. It's a nice quality of life thing for new developers. @wanseob what do you think of this?

**Comment by JChanceHud** [comment]
Ah yes, I have those disabled on my machine. Getting the tests to run locally is a bit of a pain, and it takes quite a while for them to run even on fast machines.

@wanseob Can we revisit disabling the pre-commit hook? I think it tends to confuse people and the CI tests are sufficient.

**Comment by praneethmendu** [comment]
I think not all the local tests have an equivalent on circleCI, if I have a bit of guidance I could help with the migration. Or I could do more high priority chores. I have lots of time next couple of weeks.
